name: Pipeline
on:
  push:
    branches: ['**']
jobs:
  lint:
    name: Lint with ESLint / Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Run ESLint
        run: |
          npm install
          npm run lint
  test:
    name: Test with Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: 12.x
      - name: Run Jest
        run: |
          npm install
          npm run test:cover
  run:
    name: Run the action
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: 12.x
      - name: Run the action
        id: standard-versions
        uses: ./
      - name: Dump the action outputs
        env:
          OUTPUTS: ${{ toJson(steps.standard-versions.outputs) }}
        run: echo "$OUTPUTS"
